# Generated by Django 5.2.11 on 2026-03-02 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipeingredient_quantity_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_author', to='ledger.profile'),
        ),
    ]
