# Generated by Django 5.2.11 on 2026-03-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_recipe_profile_recipeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe_image',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='image', to='ledger.recipe'),
            preserve_default=False,
        ),
    ]
