# Generated by Django 5.2.11 on 2026-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_recipeimage_recipe_image_recipeimage_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
